apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "root1234"
    - name: MYSQL_DATABASE
      value: "innovatech"
    ports:
    - containerPort: 3306
